In [14]:
import numpy as np

In [15]:
#1. Write a Python Program to Add Two Matrices?
def matadd(arr1,arr2):
    return arr1+arr2
arr1=np.mat([[1,2],[5,8]])
arr2=np.mat([[11,10],[14,16]])
matadd(arr1,arr2)

matrix([[12, 12],
        [19, 24]])

In [19]:
#2. Write a Python Program to Multiply Two Matrices?
def matmult(arr1,arr2):
    return arr1*arr2
arr1=np.mat([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2=np.mat([[6,2],[7,11],[8,12],[9,13]])
matmult(arr1,arr2)

matrix([[ 80, 112],
        [200, 264],
        [320, 416]])

In [20]:
#3. Write a Python Program to Transpose a Matrix?
def matTranspose(mat):
    return mat.T
mat=np.mat([[1,5,9],[7,8,1]])
matTranspose(mat)

matrix([[1, 7],
        [5, 8],
        [9, 1]])

In [26]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
def sortwords(l):
    l.sort()
    return l
l=['app','map','slap','bap','rap','gap','tap']
sortwords(l)
    


['app', 'bap', 'gap', 'map', 'rap', 'slap', 'tap']

In [27]:
#5. Write a Python Program to Remove Punctuation From a String?
def Punctuation(string):
    punctuations='''!()-[]{};:'"\,<>./?@#$%^&*-~'''
    for x in string.lower():
        if x in punctuations:
            string=string.replace(x,"")
    print(string)
string="I am @@@%student $??? of, ^ () % Ineuron!~"
Punctuation(string)

I am student  of    Ineuron
